version: 2
jobs:
  build:
  working_directory:~/CucumberFramework
  
  docker: # run the steps with Docker
    - image: circleci/openjdk:8-jdk-browsers
      steps:
      - checkout
      - run: mvn clean test







    


